include:
  - project: 'general/ci-templates'
    file: 'workflow.gitlab-ci.yml'

  - project: 'general/ci-templates'
    file: 'maven.gitlab-ci.yml'

  - project: 'general/ci-templates'
    file: 'docker-img.gitlab-ci.yml'

variables:
  IMG_PUSH_LATEST: 'yes'
  IMG_PUSH_UNSTABLE: 'yes'
  DOCKER_IMAGE_NAME: forward-auth-server
  DOCKER_NAMESPACE: sealife
  MAVEN_VERSION: 3.6-jdk-13
  MAVEN_SETTINGS_FILE: .docker/settings.xml
  VUE_APP_CI_COMMIT_SHORT_SHA: "$CI_JOB_ID"
  MAVEN_PREPARE_SCRIPT: "" # will be set to empty string to prevent executing VW-script

mvn test:
  artifacts:
    reports:
      junit: ./**/target/surefire-reports/TEST*.xml

mvn build (tag):
  variables:
    VUE_APP_CI_COMMIT_SHORT_SHA: "v$CI_COMMIT_TAG"

mvn deploy (release):
  variables:
    VUE_APP_CI_COMMIT_SHORT_SHA: "v$CI_COMMIT_TAG"

img publish tag remote:
  script:
    - img login -u=$DOCKER_HUB_USER -p=$DOCKER_HUB_PASSWORD
    - img tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
    - img tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:latest
    - img push $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
    - img push $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:latest
