include:
  - remote: 'https://git.virtuellewolke.de/generic/ci-templates/raw/master/maven+docker.gitlab-ci.yml'

variables:
  DOCKER_IMAGE_NAME: forward-auth-server
  DOCKER_NAMESPACE: sealife
  SKIP_MAVEN: "true"