include:
  - remote: 'https://git.virtuellewolke.de/generic/ci-templates/raw/master/maven+docker.gitlab-ci.yml'

compile maven (without version):
  rules:
    - if: '$DONOTSKIPMAVEN'

compile maven (with version):
  rules:
    - if: '$DONOTSKIPMAVEN'