include:
  - remote: 'https://git.virtuellewolke.de/generic/ci-templates/raw/master/maven+docker.gitlab-ci.yml'

variables:
  DOCKER_IMAGE_NAME: forward-auth-server
  DOCKER_NAMESPACE: sealife
  MAVEN_VERSION: 3.6-jdk-13
  MAVEN_ARGS: "-s .docker/settings.xml --batch-mode -P r3ktm8"
  VUE_APP_CI_COMMIT_SHORT_SHA: "$CI_JOB_ID"
  MAVEN_PREPARE_SCRIPT: "" # will be set to empty string to prevent executing VW-script

compile maven (with version):
  variables:
    VUE_APP_CI_COMMIT_SHORT_SHA: "v$CI_COMMIT_TAG"

docker publish tag remote:
  script:
    - docker login -u=$DOCKER_HUB_USER -p=$DOCKER_HUB_PASSWORD
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:latest
