variables:
  DOCKER_IMAGE_NAME: forward-auth-server
  DOCKER_NAMESPACE: sealife
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -P r3ktm8"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/maven-repository"


stages:
  - build
  - docker
  - publish

build-app:
  stage: build
  image: maven:3.6.2-jdk-12
  variables:
    VUE_APP_CI_COMMIT_SHORT_SHA: "$CI_COMMIT_SHORT_SHA"
  script:
    - "curl --silent https://git.r3ktm8.de/snippets/2/raw | sh"
    - "mvn $MAVEN_CLI_OPTS clean package"
  artifacts:
    paths:
      - authentication-server-core/target/*.jar

build-docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - "docker pull openjdk:12"
    - "docker build -t $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:java ."

publish-docker:
  stage: publish
  image: docker:latest
  allow_failure: true
  services:
    - docker:dind
  script:
    - "docker login -u=$DOCKER_HUB_USER -p=$DOCKER_HUB_PASSWORD"
    - "docker push $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:java"
