## System Config
server.port: 3000

## Application Configuration
app.secrets.jwt: dJHDjkahdjknsjkchnbJKHNKJWndk
cas.system-domain: http://localhost:8080

## Logging
logging.level.de.reynok: INFO

cas:
  frontend:
    clientCertAuth: true
    darkMode: false