## System Configuration
server.port: 8080

## Logging
logging.level.de.reynok: INFO

## SQL
spring.jpa.show-sql: false

## Application Defaults
cas:
  cookie-domain: localhost
  system:
    api-documentation-exposed: true

## Spring Configuration
spring:
  application:
    name: authentication-server
  boot:
    admin:
      client:
        enabled: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: "non_absent"