## System Configuration
server.port: 8080

## Logging
logging.level.de.reynok: INFO

## SQL
spring.jpa.show-sql: false

## Spring Config
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false
spring.jackson.default-property-inclusion: "non-absent"

## Application Defaults
cas.cookie-domain: localhost
cas.system.api-documentation-exposed: true