## Logging
logging.level.de.reynok: INFO

## Application Defaults
cas:
  cookie-domain: localhost
  system:
    api-documentation-exposed: true

## Spring Configuration
spring:
  application:
    name: authentication-server
  jpa:
    show-sql: false
  boot:
    admin:
      client:
        enabled: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: "non_absent"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  redis:
    enabled: true