## Logging
logging.level.de.reynok: INFO

## Spring Configuration
spring:
  application:
    name: authentication-server
  jpa:
    show-sql: false
  boot:
    admin:
      client:
        enabled: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: "non_absent"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  redis:
    enabled: false
    timeout: PT0.500S

cas:
  general:
    login-whitelist-ips:
      - '::1'
      - '127.0.0.1/32'
      - '172.16.0.1/16'